apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitproject-deployment
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitproject
  template:
    metadata:
      labels:
        app: gitproject
    spec:
      containers:
        - name: gitproject
          image: banesingh85/gitproject:a21cc3f89d406193bfd6b7a8862d64cb9d046c57
          ports:
            - containerPort: 3000    # change based on your app port
---
apiVersion: v1
kind: Service
metadata:
  name: gitproject-service
  namespace: dev
spec:
  type: NodePort       # Change to ClusterIP or NodePort if needed
  selector:
    app: gitproject
  ports:
    - port: 80
      targetPort: 3000      # same as containerPort above
      protocol: TCP
