name: Build and Push Docker Image to ECR and Deploy K8S Cluster

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t banesingh85/gitproject:${{ github.sha }} .

      - name: Push Image SHA Tag
        run: docker push banesingh85/gitproject:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUBTOKEN }}

      - name: Checking repo files
        run: |
          pwd
          ls -R

      - name: Update image tag in manifest/deployment.yaml
        run: |
          echo "Updating image tag inside manifest/deployment.yaml"
          sed -i "s|image: banesingh85/gitproject:.*|image: banesingh85/gitproject:${{ github.sha }}|g" manifest/deployment.yaml

      - name: Commit changes
        run: |
          git config user.name "banesingh85"
          git config user.email "banesingh.85@gmail.com"
          git add manifest/deployment.yaml
          git commit -m "Update image tag to ${{ github.sha }} [skip ci]"
          git push
